image: Ubuntu

stack: jdk 11

branches:
  only:
    - master

build: off

services:
  - mysql
# environment:
#   - MYSQL_RANDOM_ROOT_PASSWORD=yes
#   - MYSQL_DATABASE=app
#   - MYSQL_USER=app
#   - MYSQL_PASSWORD=pass


install:
  - java -jar ./artifacts/app-deadline.jar &


build_script:
  - chmod +x gradlew
  - ./gradlew test --info -Dselenide.headless=true