image: Ubuntu

stack: jdk 11

branches:
  only:
    - master

build: off

install:
  - java -jar ./artifacts/app-deadline.jar &


build_script:
  - chmod +x gradlew
  - ./gradlew test --info -Dselenide.headless=true