version: '3.7'
services:
  mysql:
    image: mysql:8.0
    ports:
      - '3307:3307'
    volumes:
      - ./c/Users/admin/projects/html:/usr/share/nginx/html/
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_DATABASE=app
      - MYSQL_USER=app
      - MYSQL_PASSWORD=pass
